In [4]:
import pickle

feature_bow = pickle.load(open('feature-bow.p', 'rb'))
model_nb = pickle.load(open('model-nb.p', 'rb'))
model_nn = pickle.load(open('model-nn.p', 'rb'))

c:\Users\rezaa\anaconda3\Lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator CountVectorizer from version 0.22.2.post1 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\rezaa\anaconda3\Lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator MultinomialNB from version 0.22.2.post1 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\rezaa\anaconda3\Lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator LabelBinarizer from version 0.22.2.post1 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\rezaa\anaconda3\Lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator MLPClassifier from version 0.22.2.post1 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [17]:
#predict sentiment dari kumpulan kalimat

import pandas as pd

data = pd.read_csv('data/wasit_bahrain.csv', sep=',')

In [6]:
data.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1844890448688828570,Fri Oct 11 23:58:54 +0000 2024,0,Seandainya pemimpin Indonesia setegas Bung Kar...,1844890448688828570,NaN,NaN,in,New york US,0,0,0,https://x.com/eranolok/status/1844890448688828570,1952471238,eranolok
1,1844890010266501436,Fri Oct 11 23:57:09 +0000 2024,0,Wasit Ahmed Al Kaf Sudah 4 Kali Pimpin Laga Ti...,1844890010266501436,NaN,NaN,in,"Jakarta, Indonesia",0,0,0,https://x.com/inewsdotid/status/18448900102665...,944180887171743745,inewsdotid
2,1844677613832360021,Fri Oct 11 23:51:32 +0000 2024,4,@S4ndyWijaya @Fa1zansar1 @TrollFootball Harusn...,1844888596924538987,NaN,S4ndyWijaya,in,Read my Carrd first :3c,0,1,0,https://x.com/sannawpy/status/1844888596924538987,1472033247194333187,sannawpy
3,1844805503291113547,Fri Oct 11 23:51:22 +0000 2024,3,@BahrainFA Bahrain kuat secara Finansial. Kala...,1844888554369056836,https://pbs.twimg.com/media/GZpcXL7bUAAdGep.jpg,BahrainFA,in,NaN,0,0,0,https://x.com/BojanMalisic8/status/18448885543...,1112462184460607488,BojanMalisic8
4,1844763637262750026,Fri Oct 11 23:51:14 +0000 2024,0,Akan tetapi memang seperti itu sepak bola: pro...,1844888519438893561,NaN,kompasiana,in,Indonesia,0,1,0,https://x.com/kompasiana/status/18448885194388...,23786106,kompasiana

In [7]:
data = data.rename(columns={'full_text': 'tweet'})

In [8]:
data.head()

,conversation_id_str,created_at,favorite_count,tweet,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1844890448688828570,Fri Oct 11 23:58:54 +0000 2024,0,Seandainya pemimpin Indonesia setegas Bung Kar...,1844890448688828570,NaN,NaN,in,New york US,0,0,0,https://x.com/eranolok/status/1844890448688828570,1952471238,eranolok
1,1844890010266501436,Fri Oct 11 23:57:09 +0000 2024,0,Wasit Ahmed Al Kaf Sudah 4 Kali Pimpin Laga Ti...,1844890010266501436,NaN,NaN,in,"Jakarta, Indonesia",0,0,0,https://x.com/inewsdotid/status/18448900102665...,944180887171743745,inewsdotid
2,1844677613832360021,Fri Oct 11 23:51:32 +0000 2024,4,@S4ndyWijaya @Fa1zansar1 @TrollFootball Harusn...,1844888596924538987,NaN,S4ndyWijaya,in,Read my Carrd first :3c,0,1,0,https://x.com/sannawpy/status/1844888596924538987,1472033247194333187,sannawpy
3,1844805503291113547,Fri Oct 11 23:51:22 +0000 2024,3,@BahrainFA Bahrain kuat secara Finansial. Kala...,1844888554369056836,https://pbs.twimg.com/media/GZpcXL7bUAAdGep.jpg,BahrainFA,in,NaN,0,0,0,https://x.com/BojanMalisic8/status/18448885543...,1112462184460607488,BojanMalisic8
4,1844763637262750026,Fri Oct 11 23:51:14 +0000 2024,0,Akan tetapi memang seperti itu sepak bola: pro...,1844888519438893561,NaN,kompasiana,in,Indonesia,0,1,0,https://x.com/kompasiana/status/18448885194388...,23786106,kompasiana

In [9]:
import re

def cleansing(sent):
    # Mengubah semua huruf menjadi huruf kecil
    string = sent.lower()
    
    # Menghapus URL
    string = re.sub(r'http\S+|www\S+|https\S+', '', string, flags=re.MULTILINE)
    
    # Menghapus mention (@username)
    string = re.sub(r'@\w+', '', string)
    
    # Menghapus hashtag (tetap menyimpan kata tanpa tanda '#')
    string = re.sub(r'#(\w+)', r'\1', string)
    
    # Menghapus angka dan tanda baca, hanya menyisakan huruf
    string = re.sub(r'[^a-zA-Z\s]', ' ', string)
    
    # Menghapus RT
    string = re.sub(r'\brt\b', '', string)
    
    # Menghapus whitespace berlebih
    string = re.sub(r'\s+', ' ', string).strip()
    
    return string

In [10]:
def predict_sentiment(sent):
    # cleansing
    text = cleansing(str(sent))
    # feature extraction
    text_feature = feature_bow.transform([text])
    # predict
    return model_nb.predict(text_feature)[0]

In [11]:
data['tweet'] = data.tweet.apply(cleansing)
data.head()

,conversation_id_str,created_at,favorite_count,tweet,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1844890448688828570,Fri Oct 11 23:58:54 +0000 2024,0,seandainya pemimpin indonesia setegas bung kar...,1844890448688828570,NaN,NaN,in,New york US,0,0,0,https://x.com/eranolok/status/1844890448688828570,1952471238,eranolok
1,1844890010266501436,Fri Oct 11 23:57:09 +0000 2024,0,wasit ahmed al kaf sudah kali pimpin laga timn...,1844890010266501436,NaN,NaN,in,"Jakarta, Indonesia",0,0,0,https://x.com/inewsdotid/status/18448900102665...,944180887171743745,inewsdotid
2,1844677613832360021,Fri Oct 11 23:51:32 +0000 2024,4,harusnya babak tambahan cuman menit posisi ind...,1844888596924538987,NaN,S4ndyWijaya,in,Read my Carrd first :3c,0,1,0,https://x.com/sannawpy/status/1844888596924538987,1472033247194333187,sannawpy
3,1844805503291113547,Fri Oct 11 23:51:22 +0000 2024,3,bahrain kuat secara finansial kalau main cuma ...,1844888554369056836,https://pbs.twimg.com/media/GZpcXL7bUAAdGep.jpg,BahrainFA,in,NaN,0,0,0,https://x.com/BojanMalisic8/status/18448885543...,1112462184460607488,BojanMalisic8
4,1844763637262750026,Fri Oct 11 23:51:14 +0000 2024,0,akan tetapi memang seperti itu sepak bola prot...,1844888519438893561,NaN,kompasiana,in,Indonesia,0,1,0,https://x.com/kompasiana/status/18448885194388...,23786106,kompasiana

In [12]:
data['predicted_sentiment'] = data.tweet.apply(predict_sentiment)

In [13]:
data.head()

,conversation_id_str,created_at,favorite_count,tweet,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,predicted_sentiment
0,1844890448688828570,Fri Oct 11 23:58:54 +0000 2024,0,seandainya pemimpin indonesia setegas bung kar...,1844890448688828570,NaN,NaN,in,New york US,0,0,0,https://x.com/eranolok/status/1844890448688828570,1952471238,eranolok,neutral
1,1844890010266501436,Fri Oct 11 23:57:09 +0000 2024,0,wasit ahmed al kaf sudah kali pimpin laga timn...,1844890010266501436,NaN,NaN,in,"Jakarta, Indonesia",0,0,0,https://x.com/inewsdotid/status/18448900102665...,944180887171743745,inewsdotid,positive
2,1844677613832360021,Fri Oct 11 23:51:32 +0000 2024,4,harusnya babak tambahan cuman menit posisi ind...,1844888596924538987,NaN,S4ndyWijaya,in,Read my Carrd first :3c,0,1,0,https://x.com/sannawpy/status/1844888596924538987,1472033247194333187,sannawpy,positive
3,1844805503291113547,Fri Oct 11 23:51:22 +0000 2024,3,bahrain kuat secara finansial kalau main cuma ...,1844888554369056836,https://pbs.twimg.com/media/GZpcXL7bUAAdGep.jpg,BahrainFA,in,NaN,0,0,0,https://x.com/BojanMalisic8/status/18448885543...,1112462184460607488,BojanMalisic8,negative
4,1844763637262750026,Fri Oct 11 23:51:14 +0000 2024,0,akan tetapi memang seperti itu sepak bola prot...,1844888519438893561,NaN,kompasiana,in,Indonesia,0,1,0,https://x.com/kompasiana/status/18448885194388...,23786106,kompasiana,positive

In [14]:
data.to_csv('data/dataset_predicted_sentiment_new.csv')